### PR TITLE
Better solution for doc.silverstripe.org/issues/79

### PR DESCRIPTION
**Pull request by SpiritLevel**
The better solution I proposed for https://github.com/silverstripe/doc.silverstripe.org/issues/79 seems to have been missed in the confusion of my PR titles.

### CODE REVIEW

**Comment by camfindlay** [comment]
I think this was merged into the develop branch (but not master).

**Comment by SpiritLevel** [comment]
The develop branch got my original fix, which I wanted to replace with this one. What is the best way to sort this ? Sorry for mess.

**Comment by camfindlay** [comment]
develop will likely get canned in the not too distant future so it's ok to just have this PR now.

**Comment by camfindlay** [comment]
Did you test this alongside the documentation website too?

**Comment by SpiritLevel** [comment]
Yes, but there has been a change to the head template in doc.silverstripe.org that causes a problem with running the site locally (see doc.silverstripe.org/issues/85).

**Comment by camfindlay** [comment]
you can make a temp change locally to check that if you need?

**Comment by SpiritLevel** [comment]
OK....will triple check :)

**Comment by SpiritLevel** [comment]
Works perfectly :) I tested it also when I first submitted the PR for it.

**Pull request merged**
