### PR TITLE
FIX Api shortcode link issues and updated tests

### PR DESCRIPTION
**Pull request by SpiritLevel**
Following up on silverstripe/silverstripe-docsviewer/pull/90 :)

### CODE REVIEW

**Comment by SpiritLevel** [comment]
Huh ? Tests all pass locally...suggestions anyone ?

**Comment by SpiritLevel** [comment]
Would you be willing to merge this as is if I promise to return to the commented out assert statements ? If so, then I can get back to tidying up all doc references to api, do that first, and then sort the asserts :)  Otherwise, it'll be a distraction from the main task....

**Comment by SpiritLevel** [comment]
Ping @dhensby

**Comment by SpiritLevel** [comment]
Invasion of the body snatchers! How did Damien take over my branch ??? Closing and trying again.

**Comment by tractorcow** [comment]
If you say my name three times in a mirror, I'll come and rebase your pull requests for you.

**Comment by SpiritLevel** [comment]
You're speaking in foreign tongues today, you body snatcher you!!!

I tried "fixup" instead of "squash" and buggered up my git history somehow...the PR is sorted now here and is awaiting your magic Jedi hand wave over the big green button:

silverstripe/silverstripe-docsviewer/pull/92

But, I'll keep your offer in mind for my inevitable future screw ups. :P

**Pull request closed without merging**
