### PR TITLE
API Add VersionTitle and Archived fields to config

### PR DESCRIPTION
**Pull request by tractorcow**
BUG Fix version comparison between `3` and `3.5` (3 is newer)

Developed in a backwards-compatible way so no semver breakage. :)

### CODE REVIEW

**Comment by robbieaverill** [comment]
Looks good. The PSR-2 commit I'm trusting it legit for now as it was automated. When green I'll merge.

**Comment by tractorcow** [comment]
Ah finally green. :)

**Comment by robbieaverill** [comment]
@tractorcow Your linter did a couple of strange things - just gonna push a commit to fix them up a little

**Comment by tractorcow** [comment]
Done @robbieaverill :D

**Pull request merged**
