### PR TITLE
API Use canonical URL for all repositories

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-docsviewer/issues/60

Rather than omitting the version number for the default stable branch, instead redirect from that url to the canonical version.

This would ensure that no existing stable links are broken, but ensuring that bookmarks for any page use the canonical url. If this were not the case, a page /en/my/subject would suddenly point to a different page when the next stable release version is made.

This means that we can publish links to pages in the docs, and be sure that the url of that page will not change when each release is made.

@camfindlay Once this is fixed I will update docs.silverstripe.org, and release a fix to the broken changelog links issue in silverstripe.org.

### CODE REVIEW

**Comment by tractorcow** [comment]
Also cc @dhensby and @wilr

**Comment by wilr** [comment]
@tractorcow Travis failures look related? Thanks!

**Comment by tractorcow** [comment]
Doh, I did run all the unit tests locally first. I'll fix up.

**Comment by camfindlay** [comment]
:+1:  Sounds good. Good feature to have and let me know when you are going to update docs site (we can test on the beta site first perhaps?).

**Comment by tractorcow** [comment]
Ok so a newer version of the parsedown module doesn't seem compatible with the slightly older version of parsedown-extra that we've decided to use. Adding this to the composer requirements should solve that issue.

**Comment by tractorcow** [comment]
Looks like travis won't work until https://github.com/travis-ci/travis-ci/issues/3781 is fixed.

For the mean time take my word for it.

image

**Comment by tractorcow** [comment]
@wilr tests are finally passing since we fixed travis support.

**Comment by camfindlay** [comment]
@tractorcow has tagged the currently deployed version on docs.ss.org as 1.0.0 (suggest other users of this module update their composer to ref this tag). Happy to merge.

**Pull request merged**
