### PR TITLE
Test against 3.2 and 3.3

### PR DESCRIPTION
**Pull request by camfindlay**

### CODE REVIEW

**Comment by dhensby** [comment]
It's outside the scope of this PR, but we should aim to get the failures fixed before merging this to save everyone else's PRs failing the test suite

**Comment by camfindlay** [comment]
3.2 is ok, it's just 3.3 that is failing. Unsure of cause just yet.

**Comment by camfindlay** [comment]
Can we perhaps allow 3.3 to fail for now, it blocks us from getting pull requests with useful fixes for 3.1 and 3.2 sites in place.

**Comment by dhensby** [comment]
:(

**Comment by camfindlay** [comment]
Sorted this out in #78 :D Testing more php versions and 3.2 and 3 core. Still need to sort out getting passes in 3 but this shouldn't block 3.2 compatible work getting merged in :+1:

**Pull request closed without merging**
